// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpN29QkkhB-kd2lffVzpFpuKLU-H9X6bI',
    appId: '1:265402560730:web:7f89df296e0675746f35e3',
    messagingSenderId: '265402560730',
    projectId: 'myapplication-58950',
    authDomain: 'myapplication-58950.firebaseapp.com',
    storageBucket: 'myapplication-58950.appspot.com',
    measurementId: 'G-EJV7J7F1B3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaySKyKt_FYqSfnix9ZFkHSfg7Am-V1tY',
    appId: '1:265402560730:android:cf51964ff940f1566f35e3',
    messagingSenderId: '265402560730',
    projectId: 'myapplication-58950',
    storageBucket: 'myapplication-58950.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7CZQ_SzpRU3AuKfuIbP_h5PXHt2CK7t8',
    appId: '1:265402560730:ios:3dcc21d1fc314a406f35e3',
    messagingSenderId: '265402560730',
    projectId: 'myapplication-58950',
    storageBucket: 'myapplication-58950.appspot.com',
    iosClientId: '265402560730-h6ov27pa6ktigq2mh5lqlc7obunfabbr.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7CZQ_SzpRU3AuKfuIbP_h5PXHt2CK7t8',
    appId: '1:265402560730:ios:f1763d2cb97fd4936f35e3',
    messagingSenderId: '265402560730',
    projectId: 'myapplication-58950',
    storageBucket: 'myapplication-58950.appspot.com',
    iosClientId: '265402560730-m3jvcr9pkmmnaii5qj5utvffk05ciu3a.apps.googleusercontent.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
